name: nird
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - black
  - m2r2
  - mypy
  - pre-commit
  - pytest
  - pytest-cov
  - ruff
  - sphinx
  - pip
  - pip:
      - --editable .
