name: skmob
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - geopandas
  - pandas
  - pyarrow
  - python-igraph=0.11.*
  - rasterio
  - requests
  - scikit-learn
  - snkit
  - tqdm
  - xarray
  - gdal
  - pip
  - pip:
    - nismod-snail
    - fastparquet
