name: test
# refer to https://docs.github.com/en/actions/guides/building-and-testing-python
on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # refer to version status https://devguide.python.org/versions/
        python-version: ["3.8", "3.12"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies and build python module
        run: |
          python -m pip install --upgrade pip
          pip install --verbose .[dev]

      - name: Format check with black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
          version: "~= 24.2"

      - name: Lint with ruff
        run: |
          ruff check .

      - name: Test with pytest
        run: |
          pytest --cov=nird --cov-report=term-missing tests
